---
name: Build and publish docker image to AWS ECR

on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ecr-tags
        id: ecr-tags
        env:
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          DOCKER_REGISTRY=${DOCKER_REGISTRY}/cloudflared
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#ref/tags/}
          fi
          ECR_TAGS=${DOCKER_REGISTRY}:${VERSION}
          echo ::set-output name=tags::${ECR_TAGS}

      - name: Build, tag and push image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ steps.ecr-tags.outputs.tags}}
